// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: NineTailedFox
// Company      : N/A
// Licence Type : Trial - for non-commercial trial use only
// Licences     : 1
// Valid until  : 03 JAN 2020
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Connection String Name: "AuditTrailDbContext"
//     Connection String:      "Data Source=NINE-TAILED-FOX;Initial Catalog=ExampleAuditTrail;User Id=sa; password=**zapped**;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise
// Database Version       : 14.0.1000.169

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace AuditTrail_Console
{
    // AuditEntries
    public class AuditEntry
    {
        public int AuditEntryId { get; set; } // AuditEntryID (Primary key)
        public string EntitySetName { get; set; } // EntitySetName (length: 255)
        public string EntityTypeName { get; set; } // EntityTypeName (length: 255)
        public int State { get; set; } // State
        public string StateName { get; set; } // StateName (length: 255)
        public string CreatedBy { get; set; } // CreatedBy (length: 255)
        public DateTime CreatedDate { get; set; } // CreatedDate
        public string UpdateBy { get; set; } // UpdateBy (length: 255)
        public DateTime? UpdateDate { get; set; } // UpdateDate

        // Reverse navigation

        /// <summary>
        /// Child AuditEntryProperties where [AuditEntryProperties].[AuditEntryID] point to this entity (FK_dbo.AuditEntryProperties_dbo.AuditEntries_AuditEntryID)
        /// </summary>
        public virtual ICollection<AuditEntryProperty> AuditEntryProperties { get; set; } // AuditEntryProperties.FK_dbo.AuditEntryProperties_dbo.AuditEntries_AuditEntryID

        public AuditEntry()
        {
            AuditEntryProperties = new List<AuditEntryProperty>();
        }
    }

}
// </auto-generated>


