// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: NineTailedFox
// Company      : N/A
// Licence Type : Trial - for non-commercial trial use only
// Licences     : 1
// Valid until  : 03 JAN 2020
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Connection String Name: "AuditTrailDbContext"
//     Connection String:      "Data Source=NINE-TAILED-FOX;Initial Catalog=EntityFrameworkPlus;User Id=sa; password=**zapped**;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise
// Database Version       : 14.0.1000.169

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace AuditTrail_Console
{
    // AuditEntryProperties
    public class AuditEntryPropertyConfiguration : EntityTypeConfiguration<AuditEntryProperty>
    {
        public AuditEntryPropertyConfiguration()
            : this("dbo")
        {
        }

        public AuditEntryPropertyConfiguration(string schema)
        {
            ToTable("AuditEntryProperties", schema);
            HasKey(x => x.AuditEntryPropertyId);

            Property(x => x.AuditEntryPropertyId).HasColumnName(@"AuditEntryPropertyID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.AuditEntryId).HasColumnName(@"AuditEntryID").HasColumnType("int").IsRequired();
            Property(x => x.RelationName).HasColumnName(@"RelationName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.PropertyName).HasColumnName(@"PropertyName").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.OldValue).HasColumnName(@"OldValue").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.NewValue).HasColumnName(@"NewValue").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdateDate).HasColumnName(@"UpdateDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.AuditEntry).WithMany(b => b.AuditEntryProperties).HasForeignKey(c => c.AuditEntryId); // FK_dbo.AuditEntryProperties_dbo.AuditEntries_AuditEntryID
        }
    }

}
// </auto-generated>


