// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: NineTailedFox
// Company      : N/A
// Licence Type : Trial - for non-commercial trial use only
// Licences     : 1
// Valid until  : 03 JAN 2020
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Connection String Name: "AuditTrailDbContext"
//     Connection String:      "Data Source=NINE-TAILED-FOX;Initial Catalog=ExampleAuditTrail;User Id=sa; password=**zapped**;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise
// Database Version       : 14.0.1000.169

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace AuditTrail_Console
{
    // AuditEntryProperties
    public class AuditEntryProperty
    {
        public int AuditEntryPropertyId { get; set; } // AuditEntryPropertyID (Primary key)
        public int AuditEntryId { get; set; } // AuditEntryID
        public string RelationName { get; set; } // RelationName (length: 255)
        public string PropertyName { get; set; } // PropertyName (length: 255)
        public string OldValue { get; set; } // OldValue
        public string NewValue { get; set; } // NewValue
        public DateTime? CreateDate { get; set; } // CreateDate
        public DateTime? UpdateDate { get; set; } // UpdateDate

        // Foreign keys

        /// <summary>
        /// Parent AuditEntry pointed by [AuditEntryProperties].([AuditEntryId]) (FK_dbo.AuditEntryProperties_dbo.AuditEntries_AuditEntryID)
        /// </summary>
        public virtual AuditEntry AuditEntry { get; set; } // FK_dbo.AuditEntryProperties_dbo.AuditEntries_AuditEntryID
    }

}
// </auto-generated>


