// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: NineTailedFox
// Company      : N/A
// Licence Type : Trial - for non-commercial trial use only
// Licences     : 1
// Valid until  : 03 JAN 2020
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Connection String Name: "AuditTrailDbContext"
//     Connection String:      "Data Source=NINE-TAILED-FOX;Initial Catalog=ExampleAuditTrail;User Id=sa; password=**zapped**;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise
// Database Version       : 14.0.1000.169

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace AuditTrail_Console
{
    // AuditLog
    public class AuditLog
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string AuditType { get; set; } // AuditType (length: 1)
        public string TableName { get; set; } // TableName (length: 150)
        public string Pk { get; set; } // PK (length: 50)
        public string ColumnName { get; set; } // ColumnName (length: 100)
        public string OldValue { get; set; } // OldValue
        public string NewValue { get; set; } // NewValue
        public DateTime Date { get; set; } // Date
        public Guid UserId { get; set; } // UserId
        public DateTime? CreateDate { get; set; } // CreateDate
        public DateTime? UpdateDate { get; set; } // UpdateDate

        // Foreign keys

        /// <summary>
        /// Parent Person pointed by [AuditLog].([UserId]) (FK__AuditLog__UserId__398D8EEE)
        /// </summary>
        public virtual Person Person { get; set; } // FK__AuditLog__UserId__398D8EEE
    }

}
// </auto-generated>


