// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: NineTailedFox
// Company      : N/A
// Licence Type : Trial - for non-commercial trial use only
// Licences     : 1
// Valid until  : 03 JAN 2020
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Connection String Name: "AuditTrailDbContext"
//     Connection String:      "Data Source=NINE-TAILED-FOX;Initial Catalog=EntityFrameworkPlus;User Id=sa; password=**zapped**;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise
// Database Version       : 14.0.1000.169

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace AuditTrail_Console
{
    // HistoryTrackingValueAudit
    public class HistoryTrackingValueAudit
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string ColumnName { get; set; } // ColumnName
        public string OldValue { get; set; } // OldValue
        public string NewValue { get; set; } // NewValue
        public string Action { get; set; } // Action
        public bool IsDeleted { get; set; } // IsDeleted
        public Guid InsertedById { get; set; } // InsertedById
        public DateTime InsertedAt { get; set; } // InsertedAt
        public Guid UpdatedById { get; set; } // UpdatedById
        public DateTime UpdatedAt { get; set; } // UpdatedAt
        public Guid HistoryTrackingId { get; set; } // HistoryTrackingId

        // Foreign keys

        /// <summary>
        /// Parent HistoryTrackingAudit pointed by [HistoryTrackingValueAudit].([HistoryTrackingId]) (FK__HistoryTr__Histo__403A8C7D)
        /// </summary>
        public virtual HistoryTrackingAudit HistoryTrackingAudit { get; set; } // FK__HistoryTr__Histo__403A8C7D
    }

}
// </auto-generated>


