// <auto-generated />
namespace AuditTrail_Console.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_col_table_person : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_col_table_person));
        
        string IMigrationMetadata.Id
        {
            get { return "202001040359242_Add_col_table_person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
